### ISSUE TITLE
[ERROR] All goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by RazvanMacovei** [Icinga/icinga-kubernetes#64] opened 2024-03-21 15:20 UTC
Hello,

I'm trying to integrate icinga/icinga-kubernetes:edge into my Icinga setup, but I'm encountering the following error:

`I0321 15:08:42.105696       1 main.go:75] "Importing schema" logger="database"
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc0000110e0?)
	/usr/local/go/src/runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0x189eae0?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x48
golang.org/x/sync/errgroup.(*Group).Wait(0xc0000ccf00)
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:56 +0x25
main.main()
	/build/cmd/icinga-kubernetes/main.go:202 +0x15d3

goroutine 8 [select, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc00059c0d0, {0x1d1c630, 0xc0005982d0})
	/usr/local/go/src/database/sql/sql.go:1246 +0x87
created by database/sql.OpenDB in goroutine 1
	/usr/local/go/src/database/sql/sql.go:824 +0x14c

goroutine 97 [chan receive, 1 minutes]:
main.main.ErrgroupReceive.func21()
	/build/pkg/com/com.go:30 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96

goroutine 189 [select, 1 minutes]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:620 +0x9b
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 145
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:617 +0xf9

goroutine 6227 [select, 1 minutes]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:620 +0x9b
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 6196
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:617 +0xf9

goroutine 6206 [select, 1 minutes]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:620 +0x9b
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 6101
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:617 +0xf9

goroutine 6242 [select, 1 minutes]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:620 +0x9b
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 5840
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:617 +0xf9

goroutine 6241 [select, 1 minutes]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1()
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:620 +0x9b
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher in goroutine 6176
	/go/pkg/mod/github.com/go-sql-driver/mysql@v1.8.0/connection.go:617 +0xf9`

`  icinga-kubernetes:
    depends_on:
      - icingak8s-mysql
    image: icinga/icinga-kubernetes:edge
    logging: *default-logging
    volumes:
      - icinga-kubernetes:/data
      - ./init/icinga-kubernetes.yml:/config.yml
      - $HOME/.kube/config:/.kube/config

  icingak8s-mysql:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: **********
      MYSQL_DATABASE: **********
      MYSQL_USER: **********
      MYSQL_PASSWORD: **********
    image: mysql
    logging: *default-logging
    volumes:
      - icingak8s-mysql:/var/lib/mysql`
   
Do you have any idea what might be causing this error? Thank you.

**Comment by lippserd** [comment] 2024-03-21 16:22
Hi @RazvanMacovei,

Looks like the real error is shadowed due to a bug in our error handling 😢.

Please add `command: /icinga-kubernetes -v 2` to the `icinga-kubernetes` service in order to increase log verbosity and post the output once it crashes again.

Thanks and best regards,
Eric

**Comment by RazvanMacovei** [comment] 2024-03-21 16:35
Hi @lippserd ,

Here is the log output https://pastebin.com/F1dYzbj5

Thanks.
Razvan M.

**Comment by lippserd** [comment] 2024-03-22 11:50
Hi @RazvanMacovei,

Thank you for the log output. I assume that we are trying to insert data that is not (yet) compatible with the database schema. I couldn't reproduce the deadlock scenario quickly, but I found some places that could lead to it and pushed a fix. Could you please pull the image and run it again? It will still crash, but hopefully this time with the real error.

Best regards,
Eric

**Comment by RazvanMacovei** [comment] 2024-03-22 12:05
I pulled the new image and deployed the setup. Here is the new pastebin: https://pastebin.com/RNHWAX2F

Also, I've added the output from the databases to the pastebin. The tables are created, but they are all empty now. With the old image, there were some data.

**Comment by lippserd** [comment] 2024-03-22 12:55
Can you please run the following command inside the Icinga Kubernetes database:

`ALTER TABLE endpoint_target_ref MODIFY COLUMN kind varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;`

The daemon crashes because the schema only expects `pod` for `kind` but something else is being inserted. The command above relaxes the column definition so everything can be inserted.

Afterwards, please rerun the image. After some time, if it does not crash, please share the output of the following query:

`SELECT DISTINCT kind FROM endpoint_target_ref;`

> The tables are created, but they are all empty now. With the old image, there were some data.

Yeah, previously all goroutines kept running despite having an error. Now everything is terminated correctly.

**Comment by RazvanMacovei** [comment] 2024-03-22 13:27
`mysql> use kubernetes;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> ALTER TABLE endpoint_target_ref MODIFY COLUMN kind varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> SELECT DISTINCT kind FROM endpoint_target_ref;
Empty set (0.00 sec)

mysql>`

**Comment by lippserd** [comment] 2024-03-22 13:36
Daemon still crashing?

**Comment by RazvanMacovei** [comment] 2024-03-22 13:52
Yep

**Comment by lippserd** [comment] 2024-03-22 13:54
> Yep

Care to share the error? :)

**Comment by RazvanMacovei** [comment] 2024-03-22 14:01
<img width="1374" alt="image" src="https://github.com/Icinga/icinga-kubernetes/assets/25197586/bc98a602-04dd-489a-9629-6cfe93356938">

**Comment by lippserd** [comment] 2024-03-22 14:03
You have to go to config -> modules -> kubernetes -> database and select the resource you created for the database.

**Comment by RazvanMacovei** [comment] 2024-03-22 14:08
Everything looks perfect now! Thank you so much for your help!

One more thing, I've noticed that currently, there's no possibility for multi-cluster support. Could I implement any workaround here? What if I create multiple Icinga-Kubernetes containers for each cluster and connect them all to the same database?

**Comment by RazvanMacovei** [comment] 2024-03-22 15:12
Hi @lippserd 

The Icinga server has started to experience memory issues; 8GB of RAM are constantly at 100% usage due to the Icinga-Kubernetes container. I believe the application has a memory issue.

Thanks,
Razvan

**Comment by lippserd** [comment] 2024-03-23 07:30
Hi @RazvanMacovei,

> What if I create multiple Icinga-Kubernetes containers for each cluster and connect them all to the same database?

This does not work because the daemon synchronizes each resource with the database based on its name, which means that it also deletes the entries in the database for which there are no more resources. So if you connect another cluster, all entries will be deleted as the names are different. 

But, multi-cluster support will be implemented soon.

Thanks for the debugging help!

Best regards,
Eric

For reference, commits fixing this issue:

* 25a09b64dddcdf5ee076da859c7670e92e910d86
* 11a78d21fe815f665d12625fa15a9307096637ce

**Closed by lippserd** 2024-03-23 07:30 UTC

**Comment by lippserd** [comment] 2024-03-26 19:04
> Hi @lippserd
> 
> The Icinga server has started to experience memory issues; 8GB of RAM are constantly at 100% usage due to the Icinga-Kubernetes container. I believe the application has a memory issue.
> 
> Thanks, Razvan

@RazvanMacovei  Can you please open a new issue for that?
